[package]
name = "ch14"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8.5"
sha2 = "0.10.8"
tokio = { version="1.42.0", features = ["full","tracing"] }
tracing = "0.1"
tracing-subscriber = "0.3"
console-subscriber = "0.1"
async-std = "1.13.0"
