[package]
name = "ch10"
version = "0.1.0"
edition = "2024"

[dependencies]
fast-threadpool = "0.3.0"
rusty_pool = "0.7.0"
scheduled-thread-pool = "0.2.6"
threadpool = "1.8.1"
tokio = { version = "1.32.0", features = ["full"] }
scoped-thread-pool = "1.0.4"
